name: Update Order Block Data

on:
  schedule:
    - cron: "30 * * * *"  # Runs every hour, 30 minutes after raw data update

jobs:
  update-order-block-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Update Order Block Data
        run: |
          python scripts/update_order_block_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/orderblocks/*.csv
          git commit -m "Update order block data files"
          git push
        continue-on-error: true  # Skip if no changes to commit
