name: Update Order Block Data

on:
  schedule:
    - cron: "30 * * * *"  # Runs every hour, 30 minutes after raw data update
  workflow_dispatch:        # Allows manual trigger

permissions:
  contents: write

jobs:
  update-order-block-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Update Order Block Data
        run: |
          python scripts/update_order_block_data.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw/*.csv  # or data/orderblocks/*.csv, depending on the workflow
          git commit -m "Update raw data files" || echo "No changes to commit"
          git push "https://${GH_PAT}@github.com/McNultyyy/BTC-Pair-OrderBlock-Finder.git" HEAD:main
        continue-on-error: true  # Skip if no changes to commit
