name: Update Raw Data

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  update-raw-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Fetch and Update Raw Data
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        run: |
          python scripts/update_raw_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw/*.csv
          git commit -m "Update raw data files"
          git push
        continue-on-error: true  # Skip if no changes to commit
